import ProductTagContainer from "./ProductTagContainer";

// light tags
import Tag_Light_1 from "../assets/Tags/Bubble1-Light.png";
import Tag_Light_2 from "../assets/Tags/Bubble2-Light.png";
import Tag_Light_3 from "../assets/Tags/Bubble3-Light.png";
import Tag_Light_4 from "../assets/Tags/Bubble4-Light.png";
import Tag_Light_5 from "../assets/Tags/Bubble5-Light.png";
import Tag_Light_6 from "../assets/Tags/Bubble6-Light.png";
import Tag_Light_7 from "../assets/Tags/Bubble7-Light.png";
import Tag_Light_8 from "../assets/Tags/Bubble8-Light.png";
import Tag_Light_9 from "../assets/Tags/Bubble9-Light.png";

// dark tags
import Tag_Dark_1 from "../assets/Tags/Bubble1-Dark.png";
import Tag_Dark_2 from "../assets/Tags/Bubble2-Dark.png";
import Tag_Dark_3 from "../assets/Tags/Bubble3-Dark.png";
import Tag_Dark_4 from "../assets/Tags/Bubble4-Dark.png";
import Tag_Dark_5 from "../assets/Tags/Bubble5-Dark.png";
import Tag_Dark_6 from "../assets/Tags/Bubble6-Dark.png";
import Tag_Dark_7 from "../assets/Tags/Bubble7-Dark.png";
import Tag_Dark_8 from "../assets/Tags/Bubble8-Dark.png";
import Tag_Dark_9 from "../assets/Tags/Bubble9-Dark.png";

// Part Images
import Part1_1 from "../assets/Parts/Part1-1.png";
import Part2_1 from "../assets/Parts/Part2-1.png";
import Part3_1 from "../assets/Parts/Part3-1.jpg";
import Part4_1 from "../assets/Parts/Part4-1.png";
import Part5_1 from "../assets/Parts/Part5-1.png";
import Part6_1 from "../assets/Parts/Part6-1.png";
import Part7_1 from "../assets/Parts/Part7-1.png";
import Part8_1 from "../assets/Parts/Part8-1.png";
import Part9_1 from "../assets/Parts/Part9-1.png";

//Styling selected number with details containing image, title, description.
//Styling tags positions and light, dark tag image as well.
const ProductTagDetails = [
    {
        id: 1,
        name: "Tag 1",
        image: Tag_Light_1,
        imageDark: Tag_Dark_1,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "52%",  //for smaller
                xs: "72%",  //for XSmaller Screen
                xps: "72%", //for XPSmaller Screen
                xpxs: "71%", //for XPXSmaller Screen
                xsm: "71%", //for XSmall Screen
                ipod: "68%",    //for iPod Screen
                md: "68%",  //for medium Screen
                lg: "57.5%",    //for larger Screen
                sp: "66%",  //for Surface Screen
                xmd: "66%", //for XMedium Screen
                nhs: "65%", //for Nesthub Screen
                bs: "65%",  //for Between Screen
                xbs: "64%", //for XBetween Screen
                xpbs: "64%",    //for XPBetween Screen
                xpxbs: "63%",
                xl: "62%",
                xbl: "62%",
                xpl: "62%",
                xpxl: "61%",
                nhms: "60.5%",   
                max: "60.5%",
                xmax: "60%",
                xpmax: "60%",
                xpxmax: "60%",
                xbmax: "60%",
                xbxmax: "59.5%",
                xxmax: "59.5%",
                xsn: "59%",
                xxsn: "58.5%",
                xxxsn: "58%",
                
            },
            bottom: {
                sm: "38%",
                xs: "34%",
                xps: "34%",
                xpxs: "33%",
                xsm: "33%",
                ipod: "34%",
                md: "34%",
                lg: "33%",
                sp: "34%",
                xmd: "33%",
                nhs: "33%",
                bs: "33%",
                xbs: "33%",
                xpbs: "33%",
                xpxbs: "33%",
                xl: "33.5%",
                xbl: "33%",
                xpl: "33%",
                xpxl: "33%",
                nhms: "34%",
                max: "33.5%",
                xmax: "33.5%",
                xpmax: "33.5%",
                xpxmax: "33.5%",
                xbmax: "33%",
                xbxmax: "33.5%",
                xxmax: "33.5%",
                xsn: "33.5%",
                xxsn: "33.5%",
                xxxsn: "33.5%",
            },
        },
        part: {
            image: Part1_1,
            title: "Detail One",
            description:
                "Memory LUXFOAM™ is convertible <span class='soft-text'> soft</span> to <span class='firm-text'>firm</span>",
        },
    },

    {
        id: 2,
        name: "Tag 2",
        image: Tag_Light_2,
        imageDark: Tag_Dark_2,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "35%",
                xs: "55%",
                xps: "55%",
                xpxs: "55%",
                xsm: "55%",
                ipod: "55%",
                md: "55%",
                lg: "52%",
                sp: "54%",
                xmd: "54%",
                nhs: "54%",
                bs: "54%",
                xbs: "54%",
                xpbs: "54%",
                xpxbs: "54%",
                xl: "54%",
                xbl: "54%",
                xpl: "54%",
                xpxl: "54%",
                nhms: "52.5%",
                max: "52.5%",
                xmax: "52.5%",
                xpmax: "52.5%",
                xpxmax: "52.5%",
                xbmax: "52.5%",
                xbxmax: "52.5%",
                xxmax: "52.5%",
                xsn: "52.5%",
                xxsn: "52.5%",
                xxxsn: "52.5%",
            },
            bottom: {
                sm: "2%",
                xs: "3%",
                xps: "3%",
                xpxs: "3%",
                xsm: "3%",
                ipod: "2%",
                md: "2%",
                lg: "1%",
                sp: "2%",
                xmd: "2%",
                nhs: "2%",
                bs: "2%",
                xbs: "2%",
                xpbs: "2%",
                xpxbs: "2%",
                xl: "2%",
                xbl: "2%",
                xpl: "2%",
                xpxl: "2%",
                nhms: "3%",
                max: "3%",
                xmax: "3%",
                xpmax: "3%",
                xpxmax: "3%",
                xbmax: "3%",
                xbxmax: "3%",
                xxmax: "3%",
                xsn: "3%",
                xxsn: "3%",
                xxxsn: "2.5%",
            },
        },
        part: {
            image: Part2_1,
            title: "Detail Two",
            description: "Lockable drawstring for quick size and softness changes.",
        },
    },
    {
        id: 3,
        name: "Tag 3",
        image: Tag_Light_3,
        imageDark: Tag_Dark_3,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "71%",
                xs: "88%",
                xps: "88%",
                xpxs: "86%",
                xsm: "84%",
                ipod: "81%",
                md: "79%",
                lg: "63%",
                sp: "78%",
                xmd: "76%",
                nhs: "75.5%",
                bs: "75%",
                xbs: "74%",
                xpbs: "73%",
                xpxbs: "72%",
                xl: "71%",
                xbl: "71%",
                xpl: "70%",
                xpxl: "69%",
                nhms: "68%",
                max: "67.5%",
                xmax: "67%",
                xpmax: "67%",
                xpxmax: "66.5%",
                xbmax: "66%",
                xbxmax: "65.5%",
                xxmax: "65%",
                xsn: "64.5%",
                xxsn: "64%",
                xxxsn: "63.5%",
            },
            bottom: {
                sm: "48%",
                xs: "43%",
                xps: "43%",
                xpxs: "43%",
                xsm: "43%",
                ipod: "42%",
                md: "42%",
                lg: "42%",
                sp: "43%",
                xmd: "42%",
                nhs: "43%",
                bs: "43%",
                xbs: "43%",
                xpbs: "43%",
                xpxbs: "43%",
                xl: "43%",
                xbl: "43%",
                xpl: "43%",
                xpxl: "43%",
                nhms: "43%",
                max: "43%",
                xmax: "42%",
                xpmax: "42%",
                xpxmax: "42%",
                xbmax: "42%",
                xbxmax: "42%",
                xxmax: "42%",
                xsn: "42%",
                xxsn: "42%",
                xxxsn: "42%",
            },
        },
        part: {
            image: Part3_1,
            title: "Detail Three ",
            description:
                "Breathable, washable, hypoallergenic 3D mesh cover keeps you cool and dry.",
        },
    },
    {
        id: 4,
        name: "Tag 4",
        image: Tag_Light_4,
        imageDark: Tag_Dark_4,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "25%",
                xs: "48%",
                xps: "48%",
                xpxs: "48%",
                xsm: "48%",
                ipod: "48%",
                md: "48%",
                lg: "49%",
                sp: "49%",
                xmd: "49%",
                nhs: "49%",
                bs: "49%",
                xbs: "49%",
                xpbs: "49%",
                xpxbs: "49%",
                xl: "49%",
                xbl: "49%",
                xpl: "49%",
                xpxl: "49%",
                nhms: "49%",
                max: "49%",
                xmax: "49%",
                xpmax: "49%",
                xpxmax: "49%",
                xbmax: "49%",
                xbxmax: "49%",
                xxmax: "49%",
                xsn: "49%",
                xxsn: "49%",
                xxxsn: "49%",
            },
            bottom: {
                sm: "10%",
                xs: "11%",
                xps: "11%",
                xpxs: "11%",
                xsm: "11%",
                ipod: "11%",
                md: "11%",
                lg: "10%",
                sp: "11%",
                xmd: "11%",
                nhs: "11%",
                bs: "11%",
                xbs: "11%",
                xpbs: "11%",
                xpxbs: "11%",
                xl: "11%",
                xbl: "11%",
                xpl: "11%",
                xpxl: "11%",
                nhms: "11%",
                max: "11%",
                xmax: "11%",
                xpmax: "11%",
                xpxmax: "11%",
                xbmax: "11%",
                xbxmax: "11%",
                xxmax: "11%",
                xsn: "11%",
                xxsn: "11%",
                xxxsn: "11%",
            },
        },
        part: {
            image: Part4_1,
            title: "Detail Four",
            description: "Spring loaded clasps. <br/> Quick release and secure.",
        },
    },
    {
        id: 5,
        name: "Tag 5",
        image: Tag_Light_5,
        imageDark: Tag_Dark_5,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "78%",
                xs: "95%",
                xps: "94%",
                xpxs: "92%",
                xsm: "89%",
                ipod: "86.5%",
                md: "84.5%",
                lg: "65%",
                sp: "83%",
                xmd: "82%",
                nhs: "80%",
                bs: "79%",
                xbs: "78%",
                xpbs: "77%",
                xpxbs: "76%",
                xl: "75%",
                xbl: "74%",
                xpl: "73%",
                xpxl: "72%",
                nhms: "72%",
                max: "71%",
                xmax: "71%",
                xpmax: "70.5%",
                xpxmax: "70%",
                xbmax: "69.5%",
                xbxmax: "68.5%",
                xxmax: "68%",
                xsn: "67.5%",
                xxsn: "67%",
                xxxsn: "66.7%",
            },
            bottom: {
                sm: "68%",
                xs: "58%",
                xps: "58%",
                xpxs: "58%",
                xsm: "59%",
                ipod: "59%",
                md: "59.5%",
                lg: "59%",
                sp: "58%",
                xmd: "58%",
                nhs: "59%",
                bs: "58%",
                xbs: "58%",
                xpbs: "58%",
                xpxbs: "58%",
                xl: "58%",
                xbl: "58%",
                xpl: "59%",
                xpxl: "59%",
                nhms: "58%",
                max: "59%",
                xmax: "58%",
                xpmax: "58%",
                xpxmax: "58.5%",
                xbmax: "58.5%",
                xbxmax: "59%",
                xxmax: "58.5%",
                xsn: "58%",
                xxsn: "58%",
                xxxsn: "57.5%",
            },
        },
        part: {
            image: Part5_1,
            title: "Detail Five",
            description:
                "Exercise grade rubber tethers & steel rings. <br/> Strong. Long lasting.",
        },
    },
    {
        id: 6,
        name: "Tag 6",
        image: Tag_Light_6,
        imageDark: Tag_Dark_6,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "32%",
                xs: "56%",
                xps: "56%",
                xpxs: "56%",
                xsm: "55%",
                ipod: "55%",
                md: "55%",
                lg: "52%",
                sp: "54%",
                xmd: "54.5%",
                nhs: "54%",
                bs: "54%",
                xbs: "54%",
                xpbs: "54%",
                xpxbs: "53.5%",
                xl: "53%",
                xbl: "53.5%",
                xpl: "53%",
                xpxl: "53%",
                nhms: "53%",
                max: "53%",
                xmax: "52.5%",
                xpmax: "52.5%",
                xpxmax: "52.5%",
                xbmax: "52.5%",
                xbxmax: "52.5%",
                xxmax: "52.5%",
                xsn: "52.3%",
                xxsn: "52.3%",
                xxxsn: "52.3%",
            },
            bottom: {
                sm: "40%",
                xs: "37%",
                xps: "37%",
                xpxs: "37%",
                xsm: "37%",
                ipod: "38%",
                md: "38%",
                lg: "37%",
                sp: "37%",
                xmd: "37%",
                nhs: "37%",
                bs: "37%",
                xbs: "37%",
                xpbs: "37%",
                xpxbs: "37%",
                xl: "37%",
                xbl: "37%",
                xpl: "37%",
                xpxl: "37%",
                nhms: "37%",
                max: "37%",
                xmax: "37%",
                xpmax: "37%",
                xpxmax: "37%",
                xbmax: "37%",
                xbxmax: "37%",
                xxmax: "37%",
                xsn: "37%",
                xxsn: "37%",
                xxxsn: "37%",
            },
        },
        part: {
            image: Part6_1,
            title: "Detail Six",
            description:
                "Adjustable seatbelt style strap fits chairs up to  32’ (81cm) wide. ",
        },
    },
    {
        id: 7,
        name: "Tag 7",
        image: Tag_Light_7,
        imageDark: Tag_Dark_7,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "41%",
                xs: "62%",
                xps: "62%",
                xpxs: "61.7%",
                xsm: "61%",
                ipod: "60.5%",
                md: "60%",
                lg: "54%",
                sp: "58.5%",
                xmd: "59%",
                nhs: "58.5%",
                bs: "58.5%",
                xbs: "58%",
                xpbs: "58%",
                xpxbs: "57.5%",
                xl: "57%",
                xbl: "57%",
                xpl: "57%",
                xpxl: "56.5%",
                nhms: "56%",
                max: "56%",
                xmax: "55.9%",
                xpmax: "55.8%",
                xpxmax: "55.8%",
                xbmax: "55.6%",
                xbxmax: "55.3%",
                xxmax: "55.3%",
                xsn: "54.9%",
                xxsn: "54.8%",
                xxxsn: "54.6%",
            },
            bottom: {
                sm: "75%",
                xs: "66%",
                xps: "66%",
                xpxs: "66%",
                xsm: "66%",
                ipod: "67%",
                md: "67%",
                lg: "65%",
                sp: "65%",
                xmd: "66%",
                nhs: "67%",
                bs: "67%",
                xbs: "67%",
                xpbs: "67%",
                xpxbs: "67%",
                xl: "67%",
                xbl: "67%",
                xpl: "67%",
                xpxl: "67%",
                nhms: "66%",
                max: "66%",
                xmax: "66%",
                xpmax: "66%",
                xpxmax: "66%",
                xbmax: "66%",
                xbxmax: "66%",
                xxmax: "66%",
                xsn: "66%",
                xxsn: "66%",
                xxxsn: "66%",
            },
        },
        part: {
            image: Part7_1,
            title: "Detail Seven",
            description:
                "Elastic expansion strap for wide seats. <br/>  Just in case.",
        },
    },
    {
        id: 8,
        name: "Tag 8",
        image: Tag_Light_8,
        imageDark: Tag_Dark_8,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "38%",
                xs: "60%",
                xps: "60%",
                xpxs: "59.5%",
                xsm: "59%",
                ipod: "58%",
                md: "57%",
                lg: "53%",
                sp: "56%",
                xmd: "56%",
                nhs: "56%",
                bs: "56%",
                xbs: "56%",
                xpbs: "56%",
                xpxbs: "55.5%",
                xl: "55.5%",
                xbl: "55%",
                xpl: "55%",
                xpxl: "55%",
                nhms: "55%",
                max: "55%",
                xmax: "54.5%",
                xpmax: "54.5%",
                xpxmax: "54.5%",
                xbmax: "54.5%",
                xbxmax: "54.5%",
                xxmax: "54.5%",
                xsn: "53.9%",
                xxsn: "53.9%",
                xxxsn: "53.9%",
            },
            bottom: {
                sm: "60%",
                xs: "53%",
                xps: "53%",
                xpxs: "53%",
                xsm: "53%",
                ipod: "52%",
                md: "52%",
                lg: "52%",
                sp: "52%",
                xmd: "52%",
                nhs: "53%",
                bs: "53%",
                xbs: "53%",
                xpbs: "53%",
                xpxbs: "53%",
                xl: "53%",
                xbl: "53%",
                xpl: "53%",
                xpxl: "53%",
                nhms: "53%",
                max: "53%",
                xmax: "53%",
                xpmax: "53%",
                xpxmax: "53%",
                xbmax: "53%",
                xbxmax: "53%",
                xxmax: "53%",
                xsn: "53%",
                xxsn: "53%",
                xxxsn: "53%",
            },
        },
        part: {
            image: Part8_1,
            title: "Detail Eight",
            description: "Detachable shoulder pad. Take comfort with you.",
        },
    },
    {
        id: 9,
        name: "Tag 9",
        image: Tag_Light_9,
        imageDark: Tag_Dark_9,
        ImageComponent: ProductTagContainer,
        position: {
            left: {
                sm: "51%",
                xs: "70%",
                xps: "70%",
                xpxs: "68%",
                xsm: "67%",
                ipod: "66%",
                md: "66%",
                lg: "57%",
                sp: "64%",
                xmd: "64%",
                nhs: "62%",
                bs: "62%",
                xbs: "62%",
                xpbs: "62%",
                xpxbs: "61%",
                xl: "60%",
                xbl: "60%",
                xpl: "60%",
                xpxl: "60%",
                nhms: "60%",
                max: "59%",
                xmax: "59%",
                xpmax: "59%",
                xpxmax: "59%",
                xbmax: "58.5%",
                xbxmax: "58%",
                xxmax: "58%",
                xsn: "57.5%",
                xxsn: "57%",
                xxxsn: "57%",
            },
            bottom: {
                sm: "12%",
                xs: "11%",
                xps: "11%",
                xpxs: "11%",
                xsm: "11%",
                ipod: "13%",
                md: "13%",
                lg: "11%",
                sp: "11%",
                xmd: "11%",
                nhs: "11%",
                bs: "11%",
                xbs: "11%",
                xpbs: "11%",
                xpxbs: "11%",
                xl: "11%",
                xbl: "11%",
                xpl: "11%",
                xpxl: "11%",
                nhms: "11.5%",
                max: "11%",
                xmax: "11%",
                xpmax: "11%",
                xpxmax: "11%",
                xbmax: "11%",
                xbxmax: "11%",
                xxmax: "11%",
                xsn: "11%",
                xxsn: "11%",
                xxxsn: "11%",
            },
        },
        part: {
            image: Part9_1,
            title: "Detail Nine",
            description:
                "Compact carry tote. Lightweight.<br/> Moisture resistant. <br/> Complimentary.",
        },
    },
];

export default ProductTagDetails;